README.md, samples/Introspect/Program.cs, samples/MediaPlayerRemote/Program.cs, samples/NetworkManager/Program.cs, src/Tmds.DBus/CodeGen/DBusAdapter.cs, src/Tmds.DBus/CodeGen/DBusAdapterTypeBuilder.cs, src/Tmds.DBus/CodeGen/DBusObjectProxy.cs, src/Tmds.DBus/CodeGen/DBusObjectProxyTypeBuilder.cs, src/Tmds.DBus/CodeGen/TypeDescription.cs, src/Tmds.DBus/Connection.cs, src/Tmds.DBus/ConnectionExtensions.cs, src/Tmds.DBus/DBusConnection.cs, src/Tmds.DBus/IConnection.cs, src/Tmds.DBus/IDBus.cs, src/Tmds.DBus/IDBusConnection.cs, src/Tmds.DBus/Protocol/IMessageStream.cs, src/Tmds.DBus/Protocol/MessageStream.cs, src/Tmds.DBus/Protocol/MethodHandler.cs, test/Tmds.DBus.Tests/ConnectionTests.cs, test/Tmds.DBus.Tests/DaemonTests.cs, test/Tmds.DBus.Tests/IPingPong.cs, test/Tmds.DBus.Tests/IPropertyObject.cs, test/Tmds.DBus.Tests/IStringOperations.cs, test/Tmds.DBus.Tests/IntrospectionTests.cs, test/Tmds.DBus.Tests/PairedMessageStream.cs, test/Tmds.DBus.Tests/PingPong.cs, test/Tmds.DBus.Tests/PropertyObject.cs, test/Tmds.DBus.Tests/StringOperations.cs, test/Tmds.DBus.Tests/TypeDescriptionTests.cs
Implement https://github.com/tmds/Tmds.DBus/issues/15
=> Remove CancellationToken

samples/MediaPlayerRemote/Program.cs, src/Tmds.DBus.Tool/Generator.cs, src/Tmds.DBus.Tool/ListCommand.cs, src/Tmds.DBus/CodeGen/PropertyTypeInspector.cs, src/Tmds.DBus/CodeGen/TypeDescription.cs, src/Tmds.DBus/Connection.cs, src/Tmds.DBus/DBusConnection.cs, src/Tmds.DBus/ObjectPath.cs, src/Tmds.DBus/OwnerChangedMatchRule.cs, src/Tmds.DBus/Protocol/MessageReader.cs, test/Tmds.DBus.Tests/ReaderTests.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/43
=> Fix deserializing dictionary throwing due to matching multiple fields

src/Tmds.DBus/AddressEntry.cs, src/Tmds.DBus/CodeGen/DBusAdapter.cs, src/Tmds.DBus/CodeGen/DBusObjectProxy.cs, src/Tmds.DBus/Connection.cs, src/Tmds.DBus/DBusConnection.cs, src/Tmds.DBus/Transports/LocalServer.cs, src/Tmds.DBus/Transports/Transport.cs, src/Tmds.DBus/Transports/TransportSocket.cs
=> add ConfigureAwait(false) everywhere

src/Tmds.DBus.Tool/Tmds.DBus.Tool.csproj
=> Tmds.DBus.Tool: Add net50 support

.github/workflows/build.yaml, src/Directory.Build.props, src/Tmds.DBus.Tool/Tmds.DBus.Tool.csproj, src/Tmds.DBus/Tmds.DBus.csproj, src/version.json
Equivalent of tmds/Tmds.LibC#65
=> Add Nerdbank.GitVersioning, SourceLink support

src/Tmds.DBus.Protocol/SocketExtensions.cs, src/Tmds.DBus/Transports/TransportSocket.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/128.
=> Fix EGAIN value for mac.

README.md
The changes reflect the following:
* Updated to latest version of Tmds.DBus (_0.5.0 to 0.10.1_).
* Targeting of .NET Standard 2.0 (_previous 1.x_) and supports up to .NET 6.
Great job on this tool!  Thank you for keeping it up to date :)
=> Updated Readme to match latest Tmds.DBus version

samples/MediaPlayerRemote/Mpris.DBus.cs, samples/MediaPlayerRemote/Program.cs, src/Tmds.DBus.Protocol/Connection.cs, src/Tmds.DBus.Protocol/DBusConnection.cs, src/Tmds.DBus.Tool/ProtocolGenerator.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/136.
=> Tool: protocol generator: include sender arg in events.

README.md
=> README: add link to affederaffe/Tmds.DBus.SourceGenerator.

docs/protocol.md
=> Fix compilation of Tmds.DBus.Protocol example.

src/Tmds.DBus.Protocol/DBusConnection.cs, test/Tmds.DBus.Protocol.Tests/ConnectionTests.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/191.
cc @madewokherd
=> Protocol: fix emitOnCapturedContext.

test/Tmds.DBus.Protocol.Tests/Tmds.DBus.Protocol.Tests.csproj, test/Tmds.DBus.Protocol.Tests/XunitSkip/XunitExtensions/SkippableFactDiscoverer.cs, test/Tmds.DBus.Protocol.Tests/XunitSkip/XunitExtensions/SkippableFactTestCase.cs, test/Tmds.DBus.Protocol.Tests/XunitSkip/XunitExtensions/SkippableTheoryDiscoverer.cs, test/Tmds.DBus.Protocol.Tests/XunitSkip/XunitExtensions/SkippableTheoryTestCase.cs, test/Tmds.DBus.Tests/ConnectionTests.cs, test/Tmds.DBus.Tests/DaemonTests.cs, test/Tmds.DBus.Tests/ReaderTests.cs, test/Tmds.DBus.Tests/ServiceNameTests.cs, test/Tmds.DBus.Tests/Tmds.DBus.Tests.csproj, test/Tmds.DBus.Tests/TransportTests.cs, test/Tmds.DBus.Tests/TypeDescriptionTests.cs, test/Tmds.DBus.Tests/WriterTests.cs, test/Tmds.DBus.Tests/XunitSkip/XunitExtensions/SkippableFactDiscoverer.cs, test/Tmds.DBus.Tests/XunitSkip/XunitExtensions/SkippableFactTestCase.cs, test/Tmds.DBus.Tests/XunitSkip/XunitExtensions/SkippableTheoryDiscoverer.cs, test/Tmds.DBus.Tests/XunitSkip/XunitExtensions/SkippableTheoryTestCase.cs
fixes all warnings produced by xUnit Analyzers
=> fix xunit warnings

Tmds.DBus.sln
=> add Visual Studio solution file

samples/Introspect/Introspect.csproj, samples/NetworkManager/NetworkManager.csproj
=> remove netcoreapp3.1 from samples

README.md, docs/protocol.md
Fixes https://github.com/tmds/Tmds.DBus/issues/224.
=> README: document how to use CI packages.

src/Tmds.DBus.Protocol/Address.cs, src/Tmds.DBus.Protocol/MessageWriter.Array.cs, src/Tmds.DBus.Protocol/MessageWriter.Basic.cs, src/Tmds.DBus.Protocol/MessageWriter.IntrospectionXml.cs, src/Tmds.DBus.Protocol/MessageWriter.Struct.cs, src/Tmds.DBus.Protocol/MessageWriter.Variant.Dynamic.cs, src/Tmds.DBus.Protocol/MessageWriter.WriteT.cs, src/Tmds.DBus.Protocol/Polyfill/Nerdbank.Streams.Sequence.cs, src/Tmds.DBus.Protocol/ProtocolConstants.cs, src/Tmds.DBus.Protocol/Reader.Array.cs, src/Tmds.DBus.Protocol/Reader.Basic.cs, src/Tmds.DBus.Protocol/Reader.Dictionary.cs, src/Tmds.DBus.Protocol/Reader.Handle.cs, src/Tmds.DBus.Protocol/Reader.ReadT.Dynamic.cs, src/Tmds.DBus.Protocol/Reader.ReadT.cs, src/Tmds.DBus.Protocol/Reader.Struct.cs, src/Tmds.DBus.Protocol/Reader.Variant.Dynamic.cs, src/Tmds.DBus.Protocol/Reader.Variant.cs, src/Tmds.DBus.Protocol/Reader.cs, src/Tmds.DBus.Protocol/ThrowHelper.cs, src/Tmds.DBus.Protocol/TypeModel.cs, src/Tmds.DBus.Protocol/VariantValue.cs, test/Tmds.DBus.Protocol.Tests/ReaderTests.cs, test/Tmds.DBus.Protocol.Tests/Tmds.DBus.Protocol.Tests.csproj, test/Tmds.DBus.Protocol.Tests/VariantValueTests.cs
Contributes to https://github.com/tmds/Tmds.DBus/issues/244.
=> Protocol: optimize reading of numeric arrays.

src/Tmds.DBus.Protocol/MessageWriter.Basic.cs, src/Tmds.DBus.Protocol/Reader.Variant.cs, src/Tmds.DBus.Protocol/VariantValue.cs, test/Tmds.DBus.Protocol.Tests/ReaderTests.cs, test/Tmds.DBus.Protocol.Tests/VariantValueTests.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/243.
=> Add VariantValue GetArray/GetDictionary.

src/Tmds.DBus.Protocol/MessageWriter.Variant.Dynamic.cs, src/Tmds.DBus.Protocol/MessageWriter.WriteT.Dynamic.cs, src/Tmds.DBus.Protocol/Polyfill/DynamicallyAccessedMemberTypes.cs, src/Tmds.DBus.Protocol/Polyfill/DynamicallyAccessedMembersAttribute.cs, src/Tmds.DBus.Protocol/Polyfill/RequiresUnreferencedCodeAttribute.cs, src/Tmds.DBus.Protocol/Reader.Array.cs, src/Tmds.DBus.Protocol/Reader.Dictionary.cs, src/Tmds.DBus.Protocol/Reader.Handle.cs, src/Tmds.DBus.Protocol/Reader.ReadT.Dynamic.cs, src/Tmds.DBus.Protocol/Reader.Struct.cs, src/Tmds.DBus.Protocol/Reader.Variant.Dynamic.cs, src/Tmds.DBus.Protocol/SocketExtensions.cs, src/Tmds.DBus.Protocol/Tmds.DBus.Protocol.csproj, src/Tmds.DBus.Protocol/TypeModel.Dynamic.cs, src/Tmds.DBus.Protocol/UnixFdCollection.cs, src/Tmds.DBus.Protocol/Variant.cs, src/Tmds.DBus.Protocol/VariantExtensions.cs, src/Tmds.DBus.Protocol/VariantValue.cs
Contributes to https://github.com/tmds/Tmds.DBus/issues/202.
=> Protocol: enable Trim/Aot analyzers.

samples/MediaPlayerRemote/Mpris.DBus.cs, samples/MediaPlayerRemote/Program.cs, src/Tmds.DBus.Protocol/Array.cs, src/Tmds.DBus.Protocol/Connection.DBus.cs, src/Tmds.DBus.Protocol/MessageWriter.Array.cs, src/Tmds.DBus.Protocol/Reader.Array.cs, src/Tmds.DBus.Protocol/Reader.ReadT.Dynamic.cs, src/Tmds.DBus.Protocol/Reader.Variant.cs, src/Tmds.DBus.Protocol/Strings.cs
Contributes to https://github.com/tmds/Tmds.DBus/issues/202.
=> Protocol: annotate ReadArray<T>/WriteArray<T> as RequiresUnreferencedCode.

samples/MediaPlayerRemote/Mpris.DBus.cs, src/Tmds.DBus.Protocol/Dict.cs, src/Tmds.DBus.Protocol/MessageWriter.Dictionary.cs, src/Tmds.DBus.Protocol/Reader.Dictionary.cs, src/Tmds.DBus.Protocol/Strings.cs
Contributes to https://github.com/tmds/Tmds.DBus/issues/202.
=> Protocol: annotate ReadDictionary<TKey, TValue>/WriteDictionary<TKey, TValue> as RequiresUnreferencedCode.

src/Tmds.DBus.Protocol/MessageWriter.Struct.cs, src/Tmds.DBus.Protocol/Reader.Struct.cs, src/Tmds.DBus.Protocol/Strings.cs
Contributes to https://github.com/tmds/Tmds.DBus/issues/202.
=> Protocol: annotation ReadStruct<>/WriteStruct<> as RequiresUnreferencedCode.

docs/protocol.md, src/Tmds.DBus.Protocol/Reader.Array.cs, src/Tmds.DBus.Protocol/Reader.Dictionary.cs, src/Tmds.DBus.Protocol/Reader.ReadT.Dynamic.cs, src/Tmds.DBus.Tool/ProtocolGenerator.cs, test/Tmds.DBus.Protocol.Tests/WriterTests.cs
Closes https://github.com/tmds/Tmds.DBus/issues/202.
=> Protocol: add documentation for trimming/NativeAOT.

src/Tmds.DBus.Protocol/Connection.cs, src/Tmds.DBus.Protocol/Message.cs, src/Tmds.DBus.Protocol/MessageBuffer.cs, src/Tmds.DBus.Protocol/MessageStream.cs, src/Tmds.DBus.Protocol/SocketExtensions.cs, src/Tmds.DBus.Protocol/UnixFdCollection.cs, test/Tmds.DBus.Protocol.Tests/ConnectionTests.cs, test/Tmds.DBus.Protocol.Tests/TransportTests.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/278.
=> Protocol: allow (early) dispose of sent handles.

src/Tmds.DBus/CodeGen/MethodDescription.cs, src/Tmds.DBus/CodeGen/TypeDescription.cs, test/Tmds.DBus.Tests/ConnectionTests.cs, test/Tmds.DBus.Tests/DaemonTests.cs, test/Tmds.DBus.Tests/IPropertyObject.cs, test/Tmds.DBus.Tests/PropertyObject.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/298.
cc @mmuffins
=> Fix DBusInterfaceAttribute.{Set,Get}PropertyMethod/GetAllPropertiesMethod.

src/Tmds.DBus.Protocol/MessageWriter.Basic.cs, src/Tmds.DBus.Protocol/MessageWriter.Variant.cs, src/Tmds.DBus.Protocol/ProtocolConstants.cs, src/Tmds.DBus.Protocol/TypeModel.cs, src/Tmds.DBus.Protocol/VariantValue.cs, test/Tmds.DBus.Protocol.Tests/ReaderTests.cs, test/Tmds.DBus.Protocol.Tests/WriterTests.cs
Contributes to https://github.com/tmds/Tmds.DBus/issues/303.
=> MessageWriter: support writing VariantValue.

src/Tmds.DBus.Protocol/MessageWriter.Array.cs, src/Tmds.DBus.Protocol/MessageWriter.Dictionary.cs
=> add MessageWriter.WriteDictionary() overloads for VariantValue
