NuGet.Config, src/Tmds.DBus/Transports/TransportSocket.cs
When the operation completed asynchonously, the TaskCompletionSource
was read from the Read/SendContext. This was racing with the completion
handler which sets that field to null. If the completion handler ran
first, a NullReferenceException was thrown.
Fixes https://github.com/tmds/Tmds.DBus/issues/41
=> TransportSocket: fix completion race

src/Tmds.DBus/DBusConnection.cs
After replying to org.freedesktop.DBus.Introspectable.Introspect() call the code was sending UnknownMethodError, so the daemon kicked us out of the bus.
=> Fix replying to introspectable call

src/Tmds.DBus/CodeGen/ReadMethodFactory.cs, src/Tmds.DBus/Protocol/MessageReader.cs
This commit simplifies enum deserialization. The added benefit is that it can easily support latest Mono (with support for .NET 4.7.1), otherwise the code crashes within connect method, as it can't generate the delegate for the enum in a FieldCodeEntry struct.
=> Change enum deserialization code to support Mono

src/Tmds.DBus/CodeGen/DBusAdapter.cs, test/Tmds.DBus.Tests/ConnectionTests.cs
Without the await in DBusAdapter.HandleMethodCall, the handler is returned meaning the try-catch logic is ignored. This causes the exception from a method call to bubble up and crash the host process.
=> Fix method call error handling

src/Tmds.DBus/CodeGen/ReadMethodFactory.cs, src/Tmds.DBus/CodeGen/TypeDescription.cs, src/Tmds.DBus/DBusConnection.cs
When a DBus method call is made, the caller can set a flag that they don't expect a reply. If you don't honor this flag, an Exception will be thrown when you try send the reply.
I've created this patch and it seems to work for me - but @tmds you'd be best to review it.
**Example:**
Using the bluez [gatt API](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt), there is a particular method I need to export, called StartNotify().
I did this and every time I got called with StartNotify(), Tmds.DBus threw an exception. I traced it down to this:
` Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=8  ReplyCookie=21
Sender=org.freedesktop.DBus  Destination=:1.597
ErrorName=org.freedesktop.DBus.Error.AccessDenied  ErrorMessage="Rejected send message, 1 matched …
=> Fix AccessDenied error if replying to method call that don't expect reply

.travis.yml, src/Tmds.DBus.Tool/Tmds.DBus.Tool.csproj, src/Tmds.DBus/Tmds.DBus.csproj, test/Tmds.DBus.Tests/Tmds.DBus.Tests.csproj
This is just a simple upgrade of the Global tool package specifically to .NET Core 3.0 (multitargeting to 2.1 since its an LTS).
I've done some basic testing on my Fedora 30 machine and it seems like it should be compatible with both 3.0 and 2.1.
I've also updated the Travis file to pull a 3.0.100 SDK package (link taken from the [Microsoft release docs](https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0.0/3.0.0-download.md)). I'm honestly not sure if that will be enough, but we'll soon find out!
=> Update global tool package to .NET Core 3.0

src/Tmds.DBus/CodeGen/DBusAdapter.cs
This seems to be the one place where instead of async-await a blocking wait call was used.
=> Don't wait blocking in WatchSignalsAsync()

src/Tmds.DBus/DBusConnection.cs
`DBusConnection.HandleMessage` will invoke `TaskCompletionSource<Message>.SetResult`. This can cause the continuation of that task completion source to be invoked synchronously. This can cause the calling code (i.e. code which invoked a D-Bus method using Tmds.DBus) to delay or block the execution of the `HandleMessage` method and, as such, the entire D-Bus message loop.
Specify `TaskCreationOptions.RunContinuationsAsynchronously` when creating the `TaskCompletionSource` helps avoid this issue.
=> Avoid a deadlock in DBusConnection.HandleMessage

docs/howto.md, src/Tmds.DBus.Protocol/ClientConnectionOptions.cs, src/Tmds.DBus.Protocol/ConnectionOptions.cs, src/Tmds.DBus.Protocol/DBusConnection.cs, src/Tmds.DBus/ClientConnectionOptions.cs, src/Tmds.DBus/Connection.cs, src/Tmds.DBus/DBusConnection.cs, src/Tmds.DBus/Tmds.DBus.csproj
This makes the behavior introduced in https://github.com/tmds/Tmds.DBus/pull/113 an option.
@qmfrederik ptal. See rationale in the markdown file.
=> Add option for running continuations asynchronously.

src/Tmds.DBus/Transports/TransportSocket.cs
=> Do not duplicate ReadAsync in DataAvailable.

src/Tmds.DBus.Tool/Generator.cs
The generator outputs private fields as `_camelCase` rather than `_PascaCase`
As per inquiry, #170
=> Generate Private Fields as _camelCase

src/Tmds.DBus.Protocol/MessageStream.cs, src/Tmds.DBus.Protocol/SignatureReader.cs
When sending non-single-segmented buffers, only the first segment was incorrectly sent over and over again.
=> Fix sending multiple segment messages

.github/workflows/build.yaml, src/Tmds.DBus.Tool/Tmds.DBus.Tool.csproj, test/Tmds.DBus.Protocol.Tests/Tmds.DBus.Protocol.Tests.csproj, test/Tmds.DBus.Tests/Tmds.DBus.Tests.csproj
This PR adds net7.0 to the TargetTrameworks of Tmds.Dbus.Tool to fix https://github.com/tmds/Tmds.DBus/issues/176
It also updates the GitHub Workflow and the tests projects.
=> Support net7.0

src/Tmds.DBus.Protocol/MessageStream.cs, src/Tmds.DBus.Protocol/SignatureReader.cs
The `SignatureReader` is needed to parse variants in the source generator, see https://github.com/affederaffe/Tmds.DBus.SourceGenerator/blob/3e76fbf5be03b8e1360e74b8878c541d9de808cd/Tmds.DBus.SourceGenerator/DBusSourceGenerator.Classes.cs#L240
=> Make SignatureReader public

src/Tmds.DBus/Address.cs, src/Tmds.DBus/Environment.cs, src/Tmds.DBus/Tmds.DBus.csproj
This removes the need for the package references when using .NET 6.0 or newer target frameworks.
=> add .NET 6.0 target

src/Tmds.DBus.Protocol/Netstandard2_0Extensions.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/193.
=> Protocol: Fix NREs on netstandard2.0 while reading empty strings.

src/Tmds.DBus.Protocol/PlatformDetection.cs, src/Tmds.DBus/Address.cs, src/Tmds.DBus/Environment.cs
I have checked other projects and the platform name should be lower-case.
=> correct platform guard casing

src/Tmds.DBus.Tool/Tmds.DBus.Tool.csproj
With this no multi-targeting is needed.
see https://learn.microsoft.com/en-us/dotnet/core/versions/selection#control-roll-forward-behavior
=> tool: use RollForward instead of multi-target

src/Tmds.DBus.Tool/Generator.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/190.
The MessageReader and MessageWriter expect the casing to match the item keys in the dictionary.
=> Revert "Generator outputs private fields as `_camelCase` rather than `_PascalCase` (#171)"

src/Tmds.DBus.Protocol/Connection.cs, src/Tmds.DBus.Protocol/DBusConnection.cs, src/Tmds.DBus.Protocol/MatchActionException.cs, test/Tmds.DBus.Protocol.Tests/ExceptionTests.cs
This helps users identify the Observer/Connection disposed cases.
=> Protocol: add MatchActionException helper class.

src/Tmds.DBus.Protocol/Connection.DBus.cs, src/Tmds.DBus.Tool/CodeGenCommand.cs, src/Tmds.DBus.Tool/Command.cs, src/Tmds.DBus.Tool/ListCommand.cs, src/Tmds.DBus.Tool/NodeVisitor.cs, src/Tmds.DBus.Tool/Tmds.DBus.Tool.csproj
This eliminates the 'Tmds.DBus' dependency and uses 'Tmds.DBus.Protocol' for all D-Bus operations.
=> Tool: use Protocol only.

src/Tmds.DBus.Protocol/MessageWriter.Basic.cs
Bytes were erroneously written as a short.
On little endian systems this error is masked because the first byte of the short matches the byte that is written.
=> Protocol: write byte as byte.

src/Tmds.DBus/WrappedDisposable.cs
Emitting signals takes the connection lock and then the WrappedDisposable lock.
On dispose, we'd take the locks in the opposite order: WrappedDisposable lock and then connection lock through the SignalHandlerRegistration.Dispose.
This changes WrappedDisposable so it no longer holds its lock while calling SignalHandlerRegistration.Dispose.
Fixes https://github.com/tmds/Tmds.DBus/issues/279.
=> SignalHandlerRegistration/WrappedDisposable: avoid Dispose deadlock.

src/Tmds.DBus.Protocol/Connection.cs, src/Tmds.DBus.Protocol/DBusConnection.cs, src/Tmds.DBus.Protocol/IMethodHandlerDictionary.cs, src/Tmds.DBus.Protocol/PathNodeDictionary.cs, src/Tmds.DBus.Protocol/Polyfill/NullableAttributes.cs, test/Tmds.DBus.Protocol.Tests/PathNodeDictionaryTests.cs
Fixes https://github.com/tmds/Tmds.DBus/issues/225.
=> Support removing method handlers.

src/Tmds.DBus.Protocol/Variant.cs
Probably and oversight since every other constructor is also public.
Currently, the implicit operator is already public, so there is no functionality missing, it's just a matter of taste if one prefers explicit constructors or implicit conversions.
=> Make Variant(double) public

src/Directory.Build.props, src/Tmds.DBus.Protocol/Reader.Variant.cs, src/Tmds.DBus.Protocol/VariantValue.cs, src/Tmds.DBus.Protocol/VariantValueType.cs, test/Tmds.DBus.Protocol.Tests/ReaderTests.cs, test/Tmds.DBus.Protocol.Tests/VariantValueTests.cs
This makes VariantValue track information required to write back the value to the bus.
This comes with the following breaking changes:
- A variant that holds another variant is represented as a separate instance of VariantValue. The common scenario, where a variant holds an actual non-variant type, works the same as before.
- VariantValueType.VariantValue is replaced by VariantValueType.Variant.
Fixes https://github.com/tmds/Tmds.DBus/issues/282
Contributes to https://github.com/tmds/Tmds.DBus/issues/303
=> VariantValue: track nested variants and signatures for empty arrays/dictionaries. [breaking]

src/Tmds.DBus.Tool/ProtocolGenerator.cs
* generate Set-methods for writable properties only
* align argument-type of Create-methods with .ctor() of proxy types
* PropertyChanges: invalidated and changed are swapped
=> Tool: fix generated code for protocol api

src/Tmds.DBus.Protocol/Reader.Variant.cs, src/Tmds.DBus.Protocol/VariantValue.cs, test/Tmds.DBus.Protocol.Tests/VariantValueTests.cs
This causes breaking changes:
- The GetObjectPath method now returns an ObjectPath.
- The generic parameters of GetArray/GetDictionary require an 'ObjectPath' type instead of a 'string' type.
=> VariantValue: for object paths, prefer ObjectPath type over string type.

src/Tmds.DBus.Protocol/Reader.Basic.cs, src/Tmds.DBus.Protocol/Reader.ReadT.cs, src/Tmds.DBus.Protocol/Reader.Variant.cs, src/Tmds.DBus.Tool/ProtocolGenerator.cs
Rename ReadSignatureAsSignature to ReadSignature.
Add ReadSignature overload that accepts expected as ROS<byte>.
=> Reader: add ReadSignature overloads.
